### ISSUE TITLE
Android Error: Cannot run with sound null safety, because the following dependencies don't support null safety:

### ISSUE THREAD

**Issue by erperejildo** [martinrybak/after_init#4]
- package:after_init

**Comment by rafaelmaeuer** [comment]
@martinrybak are there any plans to support null safety in the future?

**Comment by 0ttik** [comment]
It should take no time to move to null-safety since code is very simple. @martinrybak, would you accept my MR if I've made one?

**Comment by rafaelmaeuer** [comment]
@0ttik thanks for the proposal, if you create a PR that would be nice, as long as @martinrybak doesn't merge it, we could already use it as temporary workaround...

Edit: nevermind, I just created #5, feel free to use it as source:
```
after_init:
  git:
    url: https://github.com/rafaelmaeuer/after_init
    ref: master
```
